# Generated by Django 6.1.1 on 2026-09-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='model1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('p', models.IntegerField()),
                ('r', models.FloatField()),
                ('t', models.FloatField()),
            ],
        ),
    ]
